# Generated by Django 5.0.5 on 2024-07-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=40, null=True)),
                ('title', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
